# Generated by Django 3.1.1 on 2020-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestproducts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('decription', models.TextField()),
                ('price', models.TextField()),
                ('another', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
