# Generated by Django 3.1.1 on 2020-09-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestproducts', '0002_auto_20200913_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productss',
            new_name='Products',
        ),
    ]
