# Generated by Django 3.1.1 on 2020-09-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestproducts', '0003_auto_20200913_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
