# Generated by Django 3.1.1 on 2020-09-14 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bestproducts', '0005_auto_20200913_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_field',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
